import {it,expect,vi} from 'vitest'
import {decisionFor,fingerprint,type RawRecord} from '../server/review/policy'
import {ReviewStore,ReviewWorker} from '../server/review/worker'
const start=Date.parse('2026-09-14T12:00:00Z')
function row(id='new'):RawRecord {const r:RawRecord={record_id:id,fields:{'任务描述':'优化抓取效果','最终效果':'更好','遇到的困难':'','解决措施':'','填写人（系统）':{id:'ou_test',name:'测试人员'},'填写时间（系统）':start,'审核提醒状态':'已发送'}};r.fields['填写审核结果']=JSON.stringify({version:1,verdict:'reject',snapshot:{task:'优化抓取效果',result:'更好',difficulty:'',solution:''},issues:[{rule:'1-1',field:'task',evidence:'优化抓取效果',suggestion:'补充目标成功率和测试次数'}],advice:'写清目标指标和验证方法。'});return r}
function fixture(rows:RawRecord[]){let now=start+900000;const store=new ReviewStore(':memory:');const api={list:vi.fn(async()=>rows),get:vi.fn(async(id:string)=>rows.find(r=>r.record_id===id)||null),remove:vi.fn(async(id:string)=>{rows=rows.filter(r=>r.record_id!==id)})};const worker=new ReviewWorker(api,store,{base:'test',table:'test',since:new Date(start).toISOString(),recordIds:['old']},()=>now);return {store,api,worker,advance:()=>now+=300001}}
it('忽略历史，收到私信成功状态后立即备份删除且只执行一次',async()=>{const t=fixture([row('old'),row()]);await t.worker.tick();expect(t.api.remove).toHaveBeenCalledWith('new');expect(t.store.get('new')?.backup).toContain('优化抓取效果');expect(t.store.get('new')?.state).toBe('deleted');await t.worker.tick();expect(t.api.remove).toHaveBeenCalledTimes(1);t.store.db.close()})
it('尚未发送或发送失败时保留，成功后无需等待直接删除',async()=>{const r=row();r.fields['审核提醒状态']='待发送';const t=fixture([r]);await t.worker.tick();expect(t.api.remove).not.toHaveBeenCalled();r.fields['审核提醒状态']='已发送';await t.worker.tick();expect(t.api.remove).toHaveBeenCalledTimes(1);t.store.db.close()})
it('删除权限失败保留备份并停止盲目重试',async()=>{const t=fixture([row()]);t.api.remove.mockRejectedValue(new Error('REVIEW_API_91403'));await t.worker.tick();await t.worker.tick();expect(t.api.remove).toHaveBeenCalledTimes(1);expect(t.store.get('new')?.state).toBe('unknown');expect(t.store.get('new')?.backup).toContain('优化抓取效果');t.store.db.close()})
it('拒绝过期快照、虚构证据、仅十天建议以及无困难时要求困难',()=>{const r=row();const change=(f:(d:any)=>void)=>{const q=row();const d=JSON.parse(String(q.fields['填写审核结果']));f(d);q.fields['填写审核结果']=JSON.stringify(d);return decisionFor(q)};expect(decisionFor(r)?.verdict).toBe('reject');r.fields['最终效果']='已补充';expect(decisionFor(r)).toBeNull();expect(change(d=>d.issues[0].evidence='不存在')).toBeNull();expect(change(d=>d.issues[0].rule='3-1')).toBeNull();expect(change(d=>d.issues[0]={rule:'D-1',field:'difficulty',evidence:'',suggestion:'填写困难'})).toBeNull()})
it('有关联子任务、父任务或缺真实填写人时保留待复核',async()=>{for(const mode of ['parent','child','creator']){const r=row(),rows=[r];if(mode==='parent')rows.push({record_id:'old',fields:{'父记录':['new']}});if(mode==='child')r.fields['父记录']=['old'];if(mode==='creator')delete r.fields['填写人（系统）'];const t=fixture(rows);await t.worker.tick();t.advance();await t.worker.tick();expect(t.api.remove).not.toHaveBeenCalled();expect(t.store.get('new')?.state).toBe('manual');t.store.db.close()}})
it('删除前任务已修改则保留',async()=>{const r=row(),t=fixture([r]);t.api.get.mockImplementation(async()=>{r.fields['最终效果']='成功率至少95%，重复100次验证';return r});await t.worker.tick();expect(t.api.remove).not.toHaveBeenCalled();t.store.db.close()})
it('通过和待复核均不删除',async()=>{for(const verdict of ['pass','uncertain']){const r=row();const d=JSON.parse(String(r.fields['填写审核结果']));d.verdict=verdict;r.fields['填写审核结果']=JSON.stringify(d);const t=fixture([r]);await t.worker.tick();expect(t.api.remove).not.toHaveBeenCalled();t.store.db.close()}})
it('审核结果不参与内容指纹，任务变化参与',()=>{const r=row(),h=fingerprint(r);r.fields['填写审核结果']='changed';expect(fingerprint(r)).toBe(h);r.fields['预计完成日期']=123;expect(fingerprint(r)).not.toBe(h)})
