import axios from 'axios'
import type {RawRecord} from './policy'
let token:{value:string;until:number}|undefined
async function auth(){if(token&&token.until>Date.now())return token.value;const {data}=await axios.post('https://open.feishu.cn/open-apis/auth/v3/tenant_access_token/internal',{app_id:process.env.FEISHU_APP_ID,app_secret:process.env.FEISHU_APP_SECRET},{timeout:15000});if(data.code!==0||!data.tenant_access_token)throw new Error('REVIEW_AUTH_FAILED');token={value:data.tenant_access_token,until:Date.now()+(data.expire-120)*1000};return token.value}
export class ReviewApi {
  constructor(private base:string,private table:string){}
  private async request(method:'GET'|'DELETE',suffix='',params:Record<string,unknown>={}){try{const {data}=await axios.request({method,url:'https://open.feishu.cn/open-apis/bitable/v1/apps/'+encodeURIComponent(this.base)+'/tables/'+encodeURIComponent(this.table)+'/records'+suffix,params,headers:{Authorization:'Bearer '+await auth()},timeout:15000,maxRedirects:0});if(data.code!==0)throw new Error('REVIEW_API_'+data.code);return data.data}catch(e){if(axios.isAxiosError(e)&&Number.isInteger(e.response?.data?.code))throw new Error('REVIEW_API_'+e.response!.data.code);if(e instanceof Error&&/^REVIEW_(API_\d+|AUTH_FAILED)$/.test(e.message))throw e;throw new Error('REVIEW_REQUEST_UNCONFIRMED')}}
  async list():Promise<RawRecord[]>{const rows:RawRecord[]=[];let next:string|undefined;const seen=new Set<string>();do{const page=await this.request('GET','',{page_size:100,page_token:next});if(!Array.isArray(page?.items))throw new Error('REVIEW_INVALID_PAGE');rows.push(...page.items);if(!page.has_more)return rows;next=page.page_token;if(!next||seen.has(next))throw new Error('REVIEW_INCOMPLETE_PAGE');seen.add(next)}while(true)}
  async get(id:string):Promise<RawRecord|null>{try{const d=await this.request('GET','/'+encodeURIComponent(id));if(!d?.record?.record_id)throw new Error('REVIEW_INVALID_RECORD');return d.record}catch(e){if(e instanceof Error&&e.message==='REVIEW_API_1254043')return null;throw e}}
  async remove(id:string){const d=await this.request('DELETE','/'+encodeURIComponent(id));if(d?.deleted!==true||d?.record_id!==id)throw new Error('REVIEW_DELETE_UNCONFIRMED')}
}
